version: '3'
services:
  drupal:
    image: drupal:8-apache
    volumes:
      - drupal:/var/www/html
    ports:
      - 8080:80
    networks:
      - net
  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    networks:
      - net
volumes:
  drupal:
networks:
  net: