version: '3'
services:
  centos1_service:
    image: centos
    container_name: centos1
    networks:
      - test_net
    tty: true
  centos2_service:
    image: centos
    container_name: centos2
    networks:
      - test_net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    tty: true
networks:
  test_net:
